[tools]
# languages I always want available
python = ["3.12"]
node = "lts"
go = "1.26"

# global tools
uv = "latest"

# TODO: replace with pypi:* and move things to specific proejcts as needed (e.g datasette doesn't need to be global)
"pypi:datasette" = { version = "latest", with = [
  "datasette-render-html",
  "datasette-render-markdown",
  "datasette-render-timestamps",
] }
"pypi:sqlite-utils" = "latest"
"pypi:litecli" = "latest"
"pypi:ptpython" = "latest"
"pypi:stackoverflow-to-sqlite" = "latest"
"pypi:tldr" = "latest"
# my tools
"pypi:backup-airtable" = "latest"
"pypi:hacker-news-to-sqlite" = "latest"
"pypi:reddit-user-to-sqlite" = "latest"
"pypi:universal-test-runner" = "latest"
"pypi:potent" = "latest"

"npm:trash-cli" = "latest"
"npm:epub-wordcount" = "latest"
"npm:will-it-play" = "latest"
"npm:yarn" = "latest"

deno = "latest" # for yt-dlp

[settings.status]
missing_tools = "always"
