# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = '${custom.directory}$all'

# Disable the package module, hiding it from the prompt completely
[git_status]
# I'd like this enabled, but it doesn't play nice with huge repos
# until I can disable it per-machine or repo, I'll deal
disabled = false

[hg_branch]
disabled = true

[docker_context]
disabled = true

[cmd_duration]
disabled = true

[golang]
format = 'using [$symbol($version)]($style) '

[character]
success_symbol = "[%](bold white)"
error_symbol = "[%](bold red)"

[directory]
disabled = true       # replaced by a custom script
style = "bold purple"
# truncation_length = 5
repo_root_style = "bold purple"                                        # match so that repo_root_format gets used
repo_root_format = '[$repo_root]($repo_root_style)[$path](bold cyan) '
home_symbol = "🏠 ~"

[git_branch]
format = '\[[$branch(:$remote_branch)]($style)\] '
style = 'bold green'

[line_break]
# disabled = true

[python]
format = '[(\($virtualenv\) )]($style)${symbol} '

[ruby]
disabled = true

[nodejs]
# todo: flag engine version mismatches
detect_files = ["package.json"]
detect_folders = []
format = '[$symbol]($style)'

[sudo]
disabled = false

[package]
# remove `is`
format = '[$symbol]($style) '

# replace the build-in directory module
# see: https://github.com/starship/starship/issues/4199
[custom.directory]
when = true
command = "truncated_git_path_2"
description = "custom calculation to get truncated path"
